TVKain/TKXDPM.VP.20231-04

- .idea/workspace.xml
- src/main/java/com/itep/hust/aimsgroup/Application.java
- src/main/java/com/itep/hust/aimsgroup/util/Screen.java
- src/main/java/module-info.java
- src/main/resources/fxml/home.fxml
- Implements the Screen class
- The Screen class is responsible for switching scenes for the application 
- Screen.java 
- The method setMainStage sets the main stage and should only be called once in the start method of the JavaFX application 
- The method setScreen creates a new Scene object with the specified FXML URL or Node and set the scene for the main stage with the newly created Scene object 
- Step 1: Go to Application.java 
- Step 2: Set the main stage with setMainStage method in the start method of the Application class 
- Step 3: Use setScreen method to set the desired screen
> feature: Implemented Screen class

- .idea/misc.xml
Creates admin login feature 
Implemented the UI for admin login 
Implemented the getByUsername in the AdminDao class 
Implemented the authenticateLogin in AdminLoginController class 
Implemented the AdminLoginViewHandler class 
Implemented the Admin model class
Wrote tests for AdminDao class 
Wrote tests for AdminLoginController class 
Add new Admin table to the aims.sqlite database 
Add 3 records to the Admin table ("khanhtv", "1"), ("khanhnd", "1"), ("khoalnd", "1")
- controller.AdminLoginController
- model.Admin
- service.dao.AdminDao
- view.AdminLoginViewHandler
The AdminLoginViewHandler is responsible for setting up the UI
The AdminLoginController is responsible for interacting with the AdminDao to perform admin authentication
- Step 1: Go to the AdminLogin screen with Screen class …
> feature: Implemented admin login feature

- .idea/workspace.xml
- src/main/java/com/itep/hust/aimsgroup/Application.java
- src/main/java/com/itep/hust/aimsgroup/controller/AdminLoginController.java
- src/main/java/com/itep/hust/aimsgroup/service/dao/AdminDao.java
- src/main/java/com/itep/hust/aimsgroup/service/dao/Dao.java
- src/main/java/com/itep/hust/aimsgroup/service/dao/SqliteMediaDao.java
- This pull request redesign the Dao interface
- Change the usage of the classes that utilize the Dao class
- AdminDao.java 
- Dao.java 
- SqliteMediaDao.java 
- AdminControllerLogin
- The Dao now include a second template parameter to represent the type of the ID field
- Step 1: Create a AdminDao object like this 
```
Dao<Admin, String> adminDao = new AdminDao();
```
- Step 2: Call get 
```
Admin admin = adminDao.get();
```
> feature: redesign dao class

- README.md
> Topic: update README.md

- src/main/java/com/itep/hust/aimsgroup/model/cart/Cart.java
- Add features to the Cart class 
- Cart.class 
- Add getQuantity method to get the quantity of the media in the cart 
- Add isInCart method to check if the cart contain a media
> feature: add getQuantity and isInCart for Cart class

- src/main/java/com/itep/hust/aimsgroup/model/cart/Cart.java
- Added getMedias method 
- Cart.java 
- The getter getMedias return an unmodifiable view of the inner hashmap, preserve encapsulation
> Feature/cart addMedias

- src/main/java/com/itep/hust/aimsgroup/view/CartMediaViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/CartViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/HomeViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/MediaHomeViewHandler.java
- src/main/resources/fxml/cart/cart.fxml
- src/main/resources/fxml/cart/media_cart.fxml
- src/main/resources/fxml/home/home.fxml
- Thêm chức năng thêm vào giỏ hàng trên màn hình home
- Thêm màn hình cart và hiển thị các media trong giỏ hàng
- HomeViewHandler
- CartViewHandler
- CartMediaHandler
- Chọn add to cart thì sẽ gọi đến phương thức add của cart
- show lên bằng cách duyệt giỏ hàng
> Featue: Add to cart + show media in cart screen

- src/main/java/com/itep/hust/aimsgroup/view/HomeViewHandler.java
- Cập nhật số lượng media trong giỏ khi thêm 1 media vào giỏ hàng
- HomeViewHandler.java
> Fix: update number of media cart in home screen

- src/main/java/com/itep/hust/aimsgroup/view/CartViewHandler.java
- src/main/resources/fxml/cart/cart.fxml
- Cập nhật set giá của giỏ hàng vào màn hình cart
- CartViewHandler
> Fix: update sub total + amount in cart screen

- README.md
- src/main/java/com/itep/hust/aimsgroup/view/HomeViewHandler.java
- Implemented search by title
- view/HomeViewHandler.java
When the user types something into the search box then hit search, the program will check to see if any title contains the search string. If an item's title contains the search string then that item will be put into a new list, after the program finishes checking all items the original item list will be swapped with the new list. If the search box is left empty the program will return the original item list.
Run the Application class, choose "continue as customer", type something into the box on the top then hit "search"
> Feature: Search by title

- src/main/java/com/itep/hust/aimsgroup/Application.java
- src/main/java/com/itep/hust/aimsgroup/model/cart/Cart.java
Analyze cohesions 
- Cart.java 
- Application.java
> topic: analyze cohesion for Cart.java and Application.java

- README.md
>  topic: update README.md

- src/main/java/com/itep/hust/aimsgroup/model/media/Media.java
- src/main/java/com/itep/hust/aimsgroup/service/dao/SqliteMediaDao.java
- Changed type of media from double -> int
- Media.java + method of this class
- sqliteMediaDAO.java
- How your's code work
- 
- Run project -> view price of media
> Fix: type of media from double -> int

- README.md
- src/main/java/com/itep/hust/aimsgroup/model/media/Media.java
- src/main/java/com/itep/hust/aimsgroup/service/dao/Dao.java
- Phân tích cohesion trong dao
- DAO
> Topic: analyze cohesion dao

- src/main/java/com/itep/hust/aimsgroup/controller/PlaceOrderController.java
- src/main/java/com/itep/hust/aimsgroup/model/order/DeliveryInfo.java
- src/main/java/com/itep/hust/aimsgroup/model/order/Order.java
- src/main/java/com/itep/hust/aimsgroup/view/CartMediaViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/CartViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/HomeViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/MediaHomeViewHandler.java
- src/main/resources/fxml/cart/media_cart.fxml
- Sửa lại cập nhật giao diện để có thể quản lý giỏ hàng ở màn hình giỏ hàng bằng spinner
- Có thể xóa media khỏi giỏ hàng
- Cập nhật sự thống nhất về số lượng media trong giỏ và trong kho thống nhất khi chuyển giữa các màn hình
- CartViewHandle.java
- HomeViewHandle.java
- MediaCartViewHandle.java
- Thêm 1 số hàm update, set lại hiển thị khi chuyển màn hình
> Fix: number of media in home + cart

- .gitignore
- pom.xml
- src/main/java/com/itep/hust/aimsgroup/Application.java
- src/main/java/com/itep/hust/aimsgroup/controller/PlaceOrderController.java
- src/main/java/com/itep/hust/aimsgroup/controller/placeorder/PlaceOrderController.java
- src/main/java/com/itep/hust/aimsgroup/controller/placeorder/validator/DeliveryInfoValidator.java
- src/main/java/com/itep/hust/aimsgroup/controller/placeorder/validator/NormalDeliveryInfoValidator.java
- src/main/java/com/itep/hust/aimsgroup/controller/placeorder/validator/RushDeliveryInfoValidator.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/DeliveryInfo.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/RushDeliveryInfo.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/factory/DeliveryInfoFactory.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/factory/NormalDeliveryInfoFactory.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/factory/RushDeliveryInfoFactory.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/type/DeliveryType.java
- src/main/java/com/itep/hust/aimsgroup/view/CartMediaViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/CartViewHandler.java
- src/main/java/com/itep/hust/aimsgroup/view/DeliveryInfoViewHandler.java
- src/main/java/module-info.java
- src/main/resources/fxml/cart/cart.fxml
- src/main/resources/fxml/delivery-info/delivery-info.fxml
- Added Delivery Info Screen and the necessary view handler, controller, and model
- DeliveryInfo.java
- RushDeliveryInfo.java 
- controller.placeorder.validator
- model.deliveryinfo.factory
- model.deliveryinfo.type
- PlaceOrderController.java
- DeliveryInfoViewHandler.java
- DeliveryInfoViewHandler uses PlaceOrderController, when submit it set the delivery info validator of the placeOrderControlelr and uses it to validate input, then it uses the deliveryInfoFactory to construct the corresponding delivery info (either DeliveryInfo or RushDeliveryInfo) 
- Uses the strategy pattern to validate input
> feature: add delivery info screen

- src/main/java/com/itep/hust/aimsgroup/controller/AdminLoginController.java
- src/main/java/com/itep/hust/aimsgroup/model/cart/Cart.java
- src/main/java/com/itep/hust/aimsgroup/model/deliveryinfo/DeliveryInfo.java
- Analyze SOLID for Cart class and AdminLoginController class
> topic: analyse solid cart, admin

- AIMS/src/main/java/com/itep/hust/aimsgroup/Application.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/model/media/Media.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/model/media/book/Book.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/model/media/cd/CD.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/model/media/cd/Track.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/model/media/dvd/DVD.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/service/dao/sqlite/SqliteMediaDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/ManagerViewHandler.java
- AIMS/src/main/java/module-info.java
- AIMS/src/main/resources/database/query.sql
- AIMS/src/main/resources/fxml/cart/cart.fxml
- AIMS/src/main/resources/fxml/cart/media_cart.fxml
- AIMS/src/main/resources/fxml/home/home.fxml
- AIMS/src/main/resources/fxml/manager/manager.fxml
- Thêm các model và update lại database và lớp sqliteMediaDAO để hiển thị thông tin media lên màn hình manager
> Update: Model to show media in manager screen

- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/admin/AdminController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/AddMediaController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/ManagerController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/validator/CheckUpdateQuantityValidator.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/validator/MediaValidator.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/validator/detail_infor/InforBookValidator.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/validator/detail_infor/InforCDValidator.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/validator/detail_infor/InforDVDValidator.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/book/AddBookViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/cd/AddCDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/dvd/AddDVDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/book/EditBookViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/cd/EditCDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/dvd/EditDVDViewHandler.java
- AIMS/src/main/resources/fxml/manager/view/cd/view_detail_cd.fxml
- AIMS/src/main/resources/fxml/manager/view/view_detail_media.fxml
- Refactor code crud media
- Thêm  1 số lớp controller và đẩy tương tác với DAO cho controller
> Refactor: add controller for CRUD media

- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/manager/ManagerController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/ManagerViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/AddMediaViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/book/AddBookViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/cd/AddCDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/add/dvd/AddDVDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/book/EditBookViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/cd/EditCDViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/manager/edit/dvd/EditDVDViewHandler.java
- thêm popup thông báo thành công khi update + add 1 media thành công
> Popup: when update + add success

- AIMS/src/main/java/com/itep/hust/aimsgroup/controller/placeorder/PlaceOrderController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/subsystem/email/javax/JavaxEmailController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/invoice/InvoiceViewHandler.java
- Update place order controller to clear the cart after payment successful
> feature: update place order controller to clear cart

- AIMS/src/main/java/com/itep/hust/aimsgroup/model/cart/Cart.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/subsystem/email/EmailSubsystem.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/subsystem/email/javax/JavaxEmailController.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/subsystem/email/javax/JavaxEmailSubsystem.java
- Updated the email system access modifier 
- Change the access modifier of abstract method to protected 
- Change all the methods of the controller for javax email subsystem to protected 
- email subsystem package
> feature: update email subsystem access modifer

- README.md
> topic: update report week14

- AIMS/src/main/java/com/itep/hust/aimsgroup/Application.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/admin/AdminCreateViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/admin/AdminUpdateViewHandler.java
- AIMS/src/main/resources/fxml/admin/admin-add.fxml
- AIMS/src/main/resources/fxml/admin/admin-update.fxml
> feature: update admin screen

- AIMS/pom.xml
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlAccountDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlAccountRoleDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlDeliveryInfoDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlInvoiceDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlMediaDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlOrderDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlOrderMediaDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/dao/mysql/MysqlRoleDao.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/persistence/database/MysqlDatabase.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/admin/AdminViewHandler.java
- AIMS/src/main/java/com/itep/hust/aimsgroup/view/login/AccountLoginViewHandler.java
- AIMS/src/main/resources/database/query_mysql.sql
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/mysql/MysqlAccountDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteAccountDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteDeliveryInfoDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteInvoiceDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteMediaDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteOrderDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteOrderMediaDaoTest.java
- AIMS/src/test/java/com/itep/hust/aimsgroup/dao/sqlite/SqliteRoleDaoTest.java
- added support for mysql database 
- added dao classes for mysql
> feature: added mysql database support

- README.md
Update BTL - Khắc phục sau khi giảng viên nhận xét
> Topic: Update readme

- README.md
> Topic/update readme.md
